#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use Math::BigInt;

my $id     = 'protein';
my $wrap   = 80;
my $n      = 0;
my $seed   = undef;
my $input  = '';
my $unique = 0;
my $protein_header = 1;
my $help   = 0;

GetOptions(
    'n=i'             => \$n,
    'id=s'            => \$id,
    'wrap=i'          => \$wrap,
    'seed=i'          => \$seed,
    'input=s'         => \$input,
    'unique!'         => \$unique,
    'protein-header!' => \$protein_header,
    'help|h'          => \$help,
) or usage(1);

usage(0) if $help;
usage(1, "--n must be positive") if $n <= 0;
usage(1, "Use either --input or a command-line protein sequence, not both")
    if $input ne '' && @ARGV;

srand($seed) if defined $seed;

my %codons = (
    A => [qw(GCT GCC GCA GCG)],
    R => [qw(CGT CGC CGA CGG AGA AGG)],
    N => [qw(AAT AAC)],
    D => [qw(GAT GAC)],
    C => [qw(TGT TGC)],
    Q => [qw(CAA CAG)],
    E => [qw(GAA GAG)],
    G => [qw(GGT GGC GGA GGG)],
    H => [qw(CAT CAC)],
    I => [qw(ATT ATC ATA)],
    L => [qw(TTA TTG CTT CTC CTA CTG)],
    K => [qw(AAA AAG)],
    M => [qw(ATG)],
    F => [qw(TTT TTC)],
    P => [qw(CCT CCC CCA CCG)],
    S => [qw(TCT TCC TCA TCG AGT AGC)],
    T => [qw(ACT ACC ACA ACG)],
    W => [qw(TGG)],
    Y => [qw(TAT TAC)],
    V => [qw(GTT GTC GTA GTG)],
    '*' => [qw(TAA TAG TGA)],
);

my $protein = read_protein();
$protein =~ s/\s+//g;
$protein = uc $protein;
usage(1, "No protein sequence was provided") if $protein eq '';

my @aa = split //, $protein;
for my $aa (@aa) {
    usage(1, "Unsupported amino acid '$aa'. Use the 20 standard one-letter amino acids; '*' is allowed for stop codons")
        if !exists $codons{$aa};
}

my $total = Math::BigInt->bone();
for my $aa (@aa) {
    $total->bmul(scalar @{ $codons{$aa} });
}

if ($unique && Math::BigInt->new($n)->bcmp($total) > 0) {
    die "Cannot emit $n unique records; this protein has only $total possible coding sequences.\n";
}

warn "Will sample $n random FASTA records from $total possible coding sequences for protein length "
    . scalar(@aa) . ".\n";

my %seen;
my $emitted = 0;
my $attempts = 0;
my $attempt_limit = $n * 1000;
$attempt_limit = 10000 if $attempt_limit < 10000;

while ($emitted < $n) {
    ++$attempts;
    die "Could not find $n unique records after $attempt_limit attempts. Try a smaller --n or omit --unique.\n"
        if $unique && $attempts > $attempt_limit;

    my $seq = random_coding_sequence();
    next if $unique && $seen{$seq}++;

    ++$emitted;
    print '>', $id, '_', $emitted;
    print " protein=$protein" if $protein_header;
    print "\n";
    print_wrapped($seq);
}

exit 0;

sub read_protein {
    if (@ARGV) {
        return join('', @ARGV);
    }

    my $fh;
    if ($input ne '') {
        open $fh, '<', $input or die "Cannot open $input: $!\n";
    } else {
        $fh = *STDIN;
    }

    my $protein = '';
    while (my $line = <$fh>) {
        chomp $line;
        next if $line =~ /^>/;
        $protein .= $line;
    }
    close $fh if $input ne '';
    return $protein;
}

sub random_coding_sequence {
    my $seq = '';
    for my $aa (@aa) {
        my $choices = $codons{$aa};
        $seq .= $choices->[ int(rand(@$choices)) ];
    }
    return $seq;
}

sub print_wrapped {
    my ($seq) = @_;
    if ($wrap <= 0) {
        print $seq, "\n";
        return;
    }
    for (my $i = 0; $i < length($seq); $i += $wrap) {
        print substr($seq, $i, $wrap), "\n";
    }
}

sub usage {
    my ($exit, $msg) = @_;
    print STDERR "$msg\n\n" if defined $msg;
    print STDERR <<"USAGE";
Usage:
  perl reverse_translate_random.pl --n 1000 --seed 1 MKT > random_nt.fa
  perl reverse_translate_random.pl --n 1000 --seed 1 < protein.fa > random_nt.fa
  perl reverse_translate_random.pl --n 1000 --seed 1 --input protein.fa > random_nt.fa

Options:
  --n INT       Number of random coding sequences to emit
  --id STR     FASTA record prefix [protein]
  --wrap INT   Wrap sequence lines at INT bases; 0 means no wrapping [80]
  --seed INT   Make random generation reproducible
  --input FILE Read protein sequence from FILE instead of STDIN
  --unique     Reject duplicate nucleotide sequences while sampling
  --no-protein-header
               Do not append protein=SEQUENCE to each FASTA header
  --help       Show this help

Notes:
  Uses the standard genetic code and emits DNA codons.
  Each output record is generated by independently choosing one synonymous
  codon for each amino acid.
USAGE
    exit $exit;
}
